### ISSUE TITLE
Please create a new tag (release) so that a working tar can be referenced

### ISSUE THREAD

**Issue by k3a** [georgmartius/vid.stab#119]
The last tag 1.1.0 won't compile on Mac arm64 due to wrongly made checks for SSE2.

While it can be patched eventually, the master branch compiles fine.
It would be helpful if you created a new tag/release so that it is easier to reference it from distro's build recipes.

Thank you

**Comment by martius-lab** [comment]
Dear k3a, 
Thanks for reporting. I created a new tag v1.1.1. Hope that helps.
