### ISSUE TITLE
Now installable via homebrew

### ISSUE THREAD

**Issue by pmeinhardt** [georgmartius/vid.stab#16]
Hey Georg,

as of yesterday, vid.stab is now easily [installable via homebrew](https://github.com/Homebrew/homebrew/pull/28090) on OS X (`brew install libvidstab` or `brew install vid.stab`).  I've also updated the [ffmpeg install script](https://github.com/Homebrew/homebrew/blob/28bd999dd769676ffd4af2e548ef1fb664aadfed/Library/Formula/ffmpeg.rb#L28) to support compilation with the vid.stab library.

I thought you may want to include a hint on this in your installation instructions to make it even easier to install vid.stab on such systems?

Thanks for the great library. I've been using it with ffmpeg recently and it worked really well.

Freundliche Grüße
Paul

**Comment by pnbv** [comment]
Homebrew no longer accepts install options. Feel free to use the following:

```
brew remove ffmpeg

brew tap pnbv/homebrew-ffmpegvidstab

brew install pnbv/homebrew-ffmpegvidstab/ffmpeg
```

Please check docs for `brew tap` and manage your own custom ffmpeg formula (for vid.stab enable only you can just duplicate mine, above)
