### ISSUE TITLE
Detect the right lib folder for 64bit systems

### ISSUE THREAD

**Issue by fduraibi** [georgmartius/vid.stab#26]
using cmake without LIB_SUFFIX=64 will always assume the lib folder to be just lib, while on 64bit Fedora for example the main folder is lib64, and lib is used for 32bit libraries.

Check this solution out: http://www.cmake.org/pipermail/cmake/2011-June/045092.html

Also the installer that is included with the binary files doesn't look for transcode under lib64.

**Comment by georgmartius** [comment]
Okay thanks.

**Comment by georgmartius** [comment]
fixed
