### ISSUE TITLE
Rapid Shaking at End of Tripod Mode Stabilized Videos

### ISSUE THREAD

**Issue by arch-salix** [georgmartius/vid.stab#27]
FFmpeg 2.6.2 / vid.stab 0.98b / libx264 144.20150223

Some tripod mode stabilized videos rapidly shake at the end of the video stream while others do not. Original videos are relatively still with minor roll/pitch/yaw which tripod mode should easily handle. While the stablized videos look great towards the beginning of the streams, the end results are unacceptable due to the instability at the end. I have run multiple passes with tripod=1 and tripod=[random referenced frame] in vidstabdetect but the instablity issues persist. 

> ffmpeg -i input -vf vidstabdetect=tripod=1:stepsize=4:mincontrast=0:result=input.trf" -f null -

> ffmpeg -i input -vf vidstabtransform=tripod=1:interpol=bicubic:input=input.trf,unsharp=5:5:0.8:3:3:0.4 -c:v libx264 -tune film -preset veryslow -crf 12 -x264opts no-fast-pskip -c:a copy input-stab.mkv

...or...

> ffmpeg -i input -vf vidstabdetect=tripod=400:stepsize=4:mincontrast=0:result=input.trf" -f null -

> ffmpeg -i input -vf vidstabtransform=tripod=1:interpol=bicubic:input=input.trf,unsharp=5:5:0.8:3:3:0.4 -c:v libx264 -tune film -preset veryslow -crf 12 -x264opts no-fast-pskip -c:a copy input-stab.mkv

...or...

> ffmpeg -i input -vf vidstabdetect=tripod=400:result=input.trf" -f null -

> ffmpeg -i input -vf vidstabtransform=tripod=1:input=input.trf,unsharp=5:5:0.8:3:3:0.4 -c:v libx264 -c:a copy input-stab.mkv

None of the above resolves the issue. Is this a known problem with tripod mode?  Current (but not elegant) workaround is to perform standard stabilization. What to do?

**Comment by georgmartius** [comment]
thanks for reporting. The issue is not known. Can you provide a short sample.

**Comment by arch-salix** [comment]
Original File [001.mkv]
http://bit.ly/1L0cdeq

>ffmpeg -i 001.mkv -vf vidstabdetect=tripod=1:stepsize=4:mincontrast=0:result=001.mkv.trf -f null -

Transformations File [001.mkv.trf]
http://bit.ly/1zWRTJA

>ffmpeg -i 001.mkv -vf vidstabtransform=tripod=1:interpol=bicubic:input=001.mkv.trf,unsharp=5:5:0.8:3:3:0.4 -c:v libx264 -tune film -preset veryslow -crf 12 -x264opts no-fast-pskip -c:a copy 001-stab.mkv

Tripod Stablized [001.mkv-stab.mkv]
http://bit.ly/1K4Dmzb

**Comment by arch-salix** [comment]
mlt 0.9.6 / FFmpeg 2.6.2 / vid.stab 0.98b

MLT XML File
http://bit.ly/1Izlbzs [001.mkv.mlt]

MLT Transformations File [vidstab.trf]
http://bit.ly/1HfdlMN

> melt 001.mkv -filter vidstab accuracy=15 stepsize=4 mincontrast=0 tripod=1 -consumer xml:001.mkv.mlt all=1

> melt 001.mkv.mlt -consumer avformat:001.mkv-stab-mlt.mkv vcodec=libx264 tune=film preset=veryslow crf=18 fast-pskip=0 acodec=pcm_s16le

MLT Tripod Stabilized File [001.mkv-stab-mlt.mkv]
http://bit.ly/1FiEFtd
 
Same results when using mlt: Visible shake towards the end of the stream...

**Comment by georgmartius** [comment]
It was not a bug but you specified: mincontrast=0
Why did you think this is advantages. In this setting all measurement fields for motion detection are used, also those that have no contrast. There the algorithm will get many many spurious motions that will add up. Just remove it and it  should be fine.

> ffmpeg -i input -vf vidstabdetect=tripod=1:stepsize=4:result=input.trf" -f null -

you can also check

It was not a bug but you specified: mincontrast=0
Why did you think this is advantages. In this setting all measurement fields for motion detection are used, also those that have no contrast. There the algorithm will get many many spurious motions that will add up. Just remove it and it  should be fine.

> ffmpeg -i input -vf vidstabdetect=tripod=1:stepsize=4:show=1:result=input.trf" input_show.avi

then you see the detection fields it is using on each frame.
