### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by thinrope** [georgmartius/vid.stab#38]
Please make new release on GitHub and please switch to [semantic versioning](http://semver.org/), i.e. 1.0.0 or 0.9.8b or something like that.

It will greatly ease the burden on package maintainers. Let me know if you need help with the procedure.

Putting 1.0=0.98 in CHANGELOG just creates more confusion than it solves. Yes mistakes do happen, handle them with grace (and roll up).

**Comment by rbrito** [comment]
Yes, @georgmartius, please, can you tag a new release?

This would make people packaging your library much easier and more used (e.g., the official Debian repositories and its derivatives like Ubuntu don't have the library).

It's just a matter of tagging something and people can grab the tarballs from here.

Thanks in advance,

Rogério Brito.

**Comment by georgmartius** [comment]
Sorry guys, I did that now. I am really ashamed that it took me so long to do something so simple. Hope it works now.

**Comment by rbrito** [comment]
Excellent, thanks. That will make it easier to integrate the library into popular distributions, making it more and more popular.

**Comment by thinrope** [comment]
Well, I haven't taken my daily caffeine dose, but this reads 1.1.0 to me, while release/tag is 1.0.0:

https://github.com/georgmartius/vid.stab/commit/9a2fa480f1dac57e71bc9e390b38d8786e2d6ea5#diff-af3b638bc2a3e6c650974192a53c7291
````
set(MAJOR_VERSION 1)
set(MINOR_VERSION 1)
set(PATCH_VERSION 0)
set(VIDSTAB_VERSION ${MAJOR_VERSION}.${MINOR_VERSION}${PATCH_VERSION})
````
You can scrap the release, fix the file and make it again (in a way move the tag). Or make a new 1.1.0 release if you intended that.

Or I'll sip my coffee and think again.

**Comment by georgmartius** [comment]
Surely, I should have had more coffee :-)
Thanks for spotting. It looks like I had some uncommited code here and did not notice it. Anyway I decided to go for 1.1.0 right away. Hope this works now. Sorry for the confusion.

**Comment by thinrope** [comment]
No problem, coffee is a necessity...
I've updated my [pkalin overlay](https://github.com/thinrope/pkalin/) for Gentoo for 1.1.0, will try another push to have it in mainline. Cheers!

**Comment by thinrope** [comment]
A year later, LoL, I made two PR (https://github.com/gentoo/gentoo/pull/8250 & https://github.com/gentoo/gentoo/pull/8251) in my attempt to have it in mainline Gentoo :-| Let's see how the wind blows today...

**Comment by thinrope** [comment]
Moving at "lite speed", LoL, LoL, a few PR and bugs and the first strike: We have vidstab in Gentoo: https://github.com/gentoo/gentoo/commit/077738eb8a9905827e615ddb1ac2e788337b1291
Now a few more hurdles and we'll have it build with ffmpeg :-/

**Comment by georgmartius** [comment]
Lol. Thanks for staying at it and keep pressing. I am happy to hear that there are good chances we get into Gentoo ;-)
