### ISSUE TITLE
Current stable release version?

### ISSUE THREAD

**Issue by ilovezfs** [georgmartius/vid.stab#42]
Based on http://public.hronopik.de/vid.stab/ and https://github.com/georgmartius/vid.stab/releases it's not clear to me whether 1.0.0 or 0.98b is the current stable release version. Could you clarify which should be in Homebrew now? Thanks!

**Comment by georgmartius** [comment]
Sorry, I made a mistake. Please use 1.1.0. I will update the website as well.

**Comment by ilovezfs** [comment]
@georgmartius Thanks https://github.com/Homebrew/homebrew-core/pull/14056.
