### ISSUE TITLE
Issues installing vid.stab enabled ffmpeg on ubuntu 17.04

### ISSUE THREAD

**Issue by amueller** [georgmartius/vid.stab#45]
I'm trying to install ffmpeg with vid.stab on ubuntu 17.04. There seems to be no ppa for this, so I'm trying to build from source. The problem is probably more in building ffmpeg but I thought you might have an idea.
I'm trying to follow [these instructions](https://scottlinux.com/2016/09/17/video-stabilization-using-vidstab-and-ffmpeg-on-linux/#comment-1885).

The problem is that the generated ffmpeg depian package conflicts with libavcodec57, but also has a runtime dependency on libchromaprint1, which in turn depends on libavcodec57. Any help would be much appreciated.

**Comment by wotanii** [comment]
This is a little late, but I build this (amoung other things) with [this Dockerfile](https://gitlab.com/wotanii/stabbot/blob/master/Dockerfile). 

I made this file, using the [official instruction](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu)

**Comment by wotanii** [comment]
Do you need additional explanation for my dockerfile, or can this issue be closed?

**Comment by amueller** [comment]
Thanks for your help!
