### ISSUE TITLE
License conflict (in transformfixedpoint.h and transformfloat.h)

### ISSUE THREAD

**Issue by zaitor** [georgmartius/vid.stab#60]
transformfixedpoint.h and transformfloat.h have a gpl2 or later + a 

 *  This work is licensed under the Creative Commons
 *  Attribution-NonCommercial-ShareAlike 2.5 License. To view a copy of
 *  this license, visit http://creativecommons.org/licenses/by-nc-sa/2.5/
 *  or send a letter to Creative Commons, 543 Howard Street, 5th Floor,
 *  San Francisco, California, 94105, USA.
 *  This EXCLUDES COMMERCIAL USAGE

Our downstream legal team says this is a no no 

Would it be possible to have this file relisenced to a "pure" gpl2 file (like the rest of the sourcedode)?
I suppose you would have go to get an OK from @ubitux for that to be "correct in legal terms".

**Comment by ubitux** [comment]
No problem for any re-licensing regarding my past contributions to vid.stab (I don't even remember touching these files).

**Comment by zaitor** [comment]
Awesome, thanks a lot both of you. I'll make a pull req.
