### ISSUE TITLE
Is global_motions.trf data meaningless?

### ISSUE THREAD

**Issue by karbiv** [georgmartius/vid.stab#74]
A file created when "debug" option is 1, global_motions.trf;
Those numbers in global_motions.trf look random.

**Comment by karbiv** [comment]
Actually, sorry, it makes sense now.
I'm developing a script for a flawless stabilization of  wide FOV cameras, converting translation to camera motion using Hugin Stitcher command line interface.

**Comment by georgmartius** [comment]
Hi, this sounds fascinating. So you stabilize/ detect motion on each part of the image separately and then want to stitch it together?

**Comment by karbiv** [comment]
I didn't notice debug option at first, just used several line to dumped to file t.x, t.y, t.alpha(angle) in C.
Script:
I convert fisheye(sony action cam) frames to rectilinear with **Hugin**, then a rectilinear video is created from those frames, for passing it to **vidstab**. I noticed that numbers in global_motion.trf(from debug option) do not differ much when full frame is stabilized or only the center part(crop filter in ffmpeg).

A rectilinear image is a tangent function of radius(from optical center). I naively thought that converting frame pixels translations(vidstab) to horizontal and vertical rotations in Hugin would do it.
Just translations from vidstab - the center of that video looks stabilized.
After converting pixel translations to rotations of camera somewhat stabilizes wide frame, but the center looks shaky again.
I though that I calculate rotations not correctly.(tangent of video FOV from center, that tangent divided by width/2, and it's a coeff for translating pixels to rotations)

Maybe it's insufficient preciseness of stabilization data...
So another idea was to separate left and right margins of a wide rectilinear frame, where movements a **amplified**, and stabilize them separately, and apply that stabilization data with coefficients. Or convert those parts in Hugin to the scale of the center part(by rotating them in Hugin towards optical center).

Anyway, I have an automatic script that does everything automatically, I'm testing approaches.

**Comment by karbiv** [comment]
A 5 seconds video, stabilization with libvidstab(global_motion.trf) and Hugin:

https://www.youtube.com/watch?v=PMCysobszdQ

Original is a fisheye video from Sony action cam, very wide field of view, converted to rectilinear projection wiht Hugin, and then rotated in Hugin using data from from global_motion.trf(libvidstab).
That shaking on margins is amplified pixel movements in center - rectilinear image/lens is a tangent funtion of radius(from optical center).

No wobbly effect, due to Hugin rotation instead of verbatim pixel translation in libvidstab transform.
It looks like it requires a more precise stabilization data, and probably it can be fetch by using margins, which are as observed - amplified movements of objects in the center.

**Comment by karbiv** [comment]
Checking again...
It just struck me that data in global_motions.trf is **before** low pass filter(Gaussian or other).
Very simple fact, but overlooked.
It's an exploratory programming in Python, so some nuances were omitted for rapid cognition.

That might be it.

**Comment by georgmartius** [comment]
Yes, the global_motions are just a dump of the detected motion, as far as I remember. 
The real processing (low-pass filtering etc) actually done in the second phase. 
One could modify the code to dump the "to be applied" transformations as well.

**Comment by karbiv** [comment]
I discovered that and implemented gaussian filter in Python for motion data in "global_motions.trf" file - same kernel and sigma parameter.(but also a simple dump fprintf(f, "...\n", t.x, t.y, t.alpha) for processed values in library's functions for comparison)
Transformations are done in Hugin Stitcher - camera's small Euler rotation instead of plane pixel shifts, so practically only first phase(vidstab detect) is used.

The data in global_motions.trf file is relative motions of each frame(after first pass detect). Library convert it  to absolute motions("relative" param) before passing to gaussian filter - cameraPathGaussian function.

I'm looking what can be done with raw data from global_motions.trf, filtering.

**Comment by georgmartius** [comment]
You have to apply the inverse of the difference between original camera path and the smoothed one.
so transform by (smoothed_absolute_transform - detected_absolute_transform).

**Comment by karbiv** [comment]
That gives food for thought. Maybe something that I missed.

Will check that, and on current stage I'm thinking about the nature about some small shakes that left(when stepping a foot on asphalt vibration):

https://www.youtube.com/watch?v=PertAsUPdOc

**Comment by karbiv** [comment]
You are talking about these lines(299-301) in _transform.c::cameraPathGaussian_ filter function:

`avg = mult_transform(&avg, 1.0/weightsum);
// high frequency must be transformed away
ts[i] = sub_transforms(&ts[i], &avg);`

I did it at the beginning, in python implementation of Gaussian filter, but there still was some logical error.
Resolved. Results are astonishing for me.
Though I need to hone particular camera lens parameters in Hugin.
I'll post comparison of videos.

**Comment by karbiv** [comment]
Original footage(fisheye): https://www.youtube.com/watch?v=-39CehRuflo

Stabilized with libvidstab and Hugin: https://www.youtube.com/watch?v=23wiSYf_ZZA

Wide stabilized video is in rectilinear projection(standard), and can be reprojected to a Panini(or similar) projection in Hugin, which geometrically would be less wide but with the same FOV.

I haven't seen software stabilization of wide FOV videos before. For some reason all demos are narrow, tunnel vision examples.
Python program that I wrote(command line) needs some simplifications of its interface.

**Comment by georgmartius** [comment]
Great, the result looks really good.

**Comment by karbiv** [comment]
Yes, that stabilization works almost like magic.
At some point it seemed to me that some fast isolated shakes are not handled in full by the library - but it turned out that during those specific fast movements the image becomes blurred for 2-3 frames even on action cameras, so it's impossible to completely compensate it, though it's unnoticeable and happens rarely only with a very shaky footage(without even selfie stick).

But.. If the algorithm blurs each frame before analysis, it could lessen the amount of that blurring if image already has motion blur.(must be expensive operation to detect)
Just a guess, it would require more code reading to verify.("gradient descent" etc)
