### ISSUE TITLE
Using vid.stab in a continous stream?

### ISSUE THREAD

**Issue by martinschilliger** [georgmartius/vid.stab#75]
I want to stream continously to a RTMP-Server using ffmpeg, which works great. Now I found vid.stab I thought about stabilizing the stream. On static files I can stabilize in one step with for example `-i "$SOURCE" -vf vidstabdetect -vf vidstabtransform=zoom=5`.

However in stream (`rtp://`-Input from GoPro) this doesn't work, it only gives the following error. If I try to use vidstabdetect only it gives no errors, but using vidstabtransform afterwards with the created file does nothing with the video.
```log
[swscaler @ 0x110571000] deprecated pixel format used, make sure you did set range correctly
[Parsed_vidstabtransform_0 @ 0x7fabdb729e00] cannot open input file transforms.trf
[Parsed_vidstabtransform_0 @ 0x7fabdb729e00] Failed to configure input pad on Parsed_vidstabtransform_0
Error reinitializing filters!
```

Any idea how I could detect and transform in one step? Or isn't this possible at all?

I want to mount the camera on a pig and stream the video, so stabilization would be great… 😂🐷

**Comment by georgmartius** [comment]
Hi,
so far the filter is implemented as a two-phase process. 
To do it online one cannot look into the future for camera movement compensation. This makes the quality worse. I have such a version in "transcode" but did not make an equivalent version for ffmpeg.

**Comment by karbiv** [comment]
Not in open source yet. Sony has their algorithm for BIONZX processor(in action cams). 60 FPS online stabilization, it must have a big memory buffer. But it passes through some shakiness and crops field of view significantly(the reason why they use very wide FOV lens).
It was their investment(besides wider FOV) to enter a competition with GoPro(which added stabilization much later).
Sony smartphones have online stabilization but pixels quality on my model is not great, and it still passes some shakiness.

Probably some multi-threading algorithm on desktop CPU(at lest 8 cores) could do that better. That would require a lot of time and research investment.

**Comment by martinschilliger** [comment]
Thank you both for the clarification. So it's clear that _it isn't technically possible right_ now with vid.stab.

I saw stabilization  on the GoPro and was impressed to see it in ffmpeg also. Your software is impressing anyway. 😊
