### ISSUE TITLE
Transforms information file naming limitations

### ISSUE THREAD

**Issue by DavidAzofeifa** [georgmartius/vid.stab#87]
It is not possible to use a transforms information file (*.trf) that contains a comma (,) or semicolon (;) on its name. Maybe there are other forbidden characters too. This is a problem when using vidstab on a parameterized batch file that takes a video file name as input, which can indeed contain such characters.

**Comment by georgmartius** [comment]
I think this is a problem of ffmpeg's command line parsing. 
colons ':' are also not allows.
I recommend create a new name for thee transform files or replace the forbidden characters in the batch script.

**Comment by DavidAzofeifa** [comment]
Yes, I solved it by replacing the commas and semicolons with underscores:

```bat
@echo off

if "%~1" == "" goto end

setlocal

set _filename=%~n1
set _extension=%~x1

set _cleanname=%_filename%
set _cleanname=%_cleanname:,=_%
set _cleanname=%_cleanname:;=_%

ffmpeg -y -i "%_filename%%_extension%" -vf vidstabdetect=shakiness=10:result="%_cleanname%.trf" -f null -

ffmpeg -y -i "%_filename%%_extension%" -vf vidstabtransform=smoothing=30:optzoom=2:zoomspeed=0.2:interpol=bicubic:input="%_cleanname%.trf" -movflags use_metadata_tags -map_metadata 0:g -preset veryfast -c:v libx264 -crf 20 "%_filename%.stable%_extension%"

del /q /a /f "%_cleanname%.trf"

endlocal
echo=

:end
```
